path:
    raw: "../../data/raw/"
    interim: "../../data/interim/"
    processed: "../../data/processed/"
    artifact: "../../artifacts/"
    udf: "../../src"
    raw_wm: "../../data/raw/walmart-recruiting-store-sales-forecasting/"